SELECT * FROM CITAS;
SELECT * FROM TATUADORES;
SELECT * FROM ANILLADORES;
SELECT * FROM CABINAS;
SELECT	ID_CABINA
	FROM CABINAS 
    WHERE PUEDE_HACER_PIERCING IS TRUE;
CALL `estudio_tattoo`.`CREAR_NUEVA_CITA`(<{IN NUEVO_TIPO VARCHAR(8)}>, <{IN NUEVA_DESCRIPCION VARCHAR(60)}>, <{IN NUEVA_SEÑAL FLOAT}>, <{IN NUEVO_PRECIO FLOAT}>, <{IN NUEVO_ESTADO CHAR(9)}>, <{IN NUEVO_TATUADOR INT UNSIGNED}>, <{IN NUEVO_ANILLADOR INT UNSIGNED}>, <{IN NUEVA_CABINA INT UNSIGNED}>);

CALL `estudio_tattoo`.`CREAR_NUEVA_CITA`("TATUAJE", "CITA PARA PROBAR", 20.0, 150.0, "RESERVADA", 1, NULL, 1); /*OK*/
CALL `estudio_tattoo`.`CREAR_NUEVA_CITA`("TATUAJE", "CITA TATTOO PROBAR", 20.0, 150.0, "REALIZADA", 5, NULL, 1); /*OK*/
CALL `estudio_tattoo`.`CREAR_NUEVA_CITA`("PIERCING", "CITA PARA PROBAR PIERCING", 20.0, 150.0, "RESERVADA", NULL, 2, 1); /*OK*/
CALL `estudio_tattoo`.`CREAR_NUEVA_CITA`("PIERCING", "CITA FSGDGDGDFG", 20.0, 150.0, "RESERVADA", NULL, 2, 4); /*OK*/
CALL `estudio_tattoo`.`CREAR_NUEVA_CITA`("PIERCING", "CITA SDAFG DGHGH SDFG", 20.0, 150.0, "REALIZADA", NULL, 2, 4); /*OK*/





