
CREATE DATABASE Estudio_Tattoo;


/** 
  * Ejemplorlr
  *    
  *
  *
  *
  **/
  
        DROP TABLE IF EXISTS TUTORES_LEGALES;
  CREATE TABLE IF NOT EXISTS TUTORES_LEGALES (
 
	DNI CHAR(9) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO VARCHAR (15) NOT NULL,
    
	PRIMARY KEY (DNI)
 
  ) ENGINE INNODB;
  
  DROP TABLE IF EXISTS CLIENTES;
  CREATE TABLE IF NOT EXISTS CLIENTES (
  
	ID_CLIENTE INTEGER AUTO_INCREMENT NOT NULL,
    DNI CHAR (9) NOT NULL,
    TELEFONO VARCHAR(15) NOT NULL,
    DIRECCIÓN VARCHAR(30) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    INSTAGRAM VARCHAR(30)  NOT NULL,
    NOMBRE VARCHAR(30)  NOT NULL,
    EMAIL VARCHAR(30)  NOT NULL,
    TUTOR  CHAR(9) NOT NULL,
    PARENTESCO ENUM("PADRE","MADRE","ABUELO","ABUELA","OTRO")NOT NULL,
    
    FOREIGN KEY (TUTOR) REFERENCES TUTORES_LEGALES(DNI)
				ON DELETE CASCADE
                ON UPDATE CASCADE,
	INDEX FK_TUTOR_LEGAL(TUTOR)
	
  ) ENGINE INNODB;
  
    DROP TABLE IF EXISTS ALERGIAS_CLIENTES;
  CREATE TABLE IF NOT EXISTS ALERGIAS_CLIENTES (
  
	ID_CLIENTE INTEGER NOT NULL,
    ALERGIA VARCHAR(30) NULL,
    
    PRIMARY KEY (ID_CLIENTE, ALERGIA),
    
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
				ON DELETE CASCADE
                ON UPDATE CASCADE,
	INDEX FK_CLIENTE_ALERGIA(ID_CLIENTE)
    
  ) ENGINE INNODB;
  



