
DELIMITER $$
USE ESTUDIO_TATTOO$$

/*FUNCION QUE DEVUELVE EL TIPO DE AGUJA AL INTRODUCIR COMO PARÁMETRO SU ID*/

DROP FUNCTION IF EXISTS  GET_TIPO_AGUJA$$
CREATE FUNCTION GET_TIPO_AGUJA(CLAVE_AGUJA INT UNSIGNED)
RETURNS VARCHAR(15)
READS SQL DATA
BEGIN
	DECLARE TIPO VARCHAR(15);
    SELECT CONCAT(NUMERO_AGUJAS,CONFIGURACION,TAPER) INTO TIPO
		FROM AGUJAS
        WHERE ID_AGUJA = CLAVE_AGUJA;
	RETURN TIPO;
END$$

/*FUNCION QUE DEVUELVE EL ID DE UNA AGUJA A PARTIR DE SU TIPO*/
DROP FUNCTION IF EXISTS  GET_ID_AGUJA$$
CREATE FUNCTION GET_ID_AGUJA(TIPO_AGUJA VARCHAR(15))
RETURNS INT UNSIGNED
READS SQL DATA
BEGIN
	DECLARE ID INT UNSIGNED;
    SELECT ID_AGUJA INTO ID
		FROM AGUJAS
        WHERE CONCAT(NUMERO_AGUJAS,CONFIGURACION,TAPER) = TIPO_AGUJA;
	RETURN ID;
END$$

/*FUNCION QUE DEVUELVE LA CANTIDAD DISPONIBLE DE AGUJAS DE UN TIPO*/
DROP FUNCTION IF EXISTS  CANTIDAD_AGUJA_TIPO$$
CREATE FUNCTION CANTIDAD_AGUJA_TIPO(TIPO_AGUJA VARCHAR(15))
RETURNS INT 
READS SQL DATA
BEGIN
	DECLARE DISPONIBLES INT UNSIGNED;
    SELECT CANTIDAD INTO DISPONIBLES
		FROM AGUJAS
        WHERE CONCAT(NUMERO_AGUJAS,CONFIGURACION,TAPER) = TIPO_AGUJA;
	IF DISPONIBLES IS NULL
		THEN RETURN 0;
        ELSE RETURN DISPONIBLES;
	END IF;
END$$

