DELIMITER $$

DROP PROCEDURE IF EXISTS CREAR_HUECOS_SEMANALES$$
CREATE PROCEDURE CREAR_HUECOS_SEMANALES(IN FECHA_INICIO DATE, IN NUM_SEMANAS INT)
MODIFIES SQL DATA
BEGIN
	DECLARE HORA_ACTUAL TIME;
    DECLARE HORA_FIN TIME;
    DECLARE CONTADOR INT;
    DECLARE DIA_SEMANA INT;
    DECLARE FECHA_ACTUAL DATE;
    DECLARE NUMERO_HUECO INT;
    
    SET HORA_ACTUAL = "11:00:00";
    SET HORA_FIN = "20:00:00";
    SET CONTADOR = 1;
    SET DIA_SEMANA = 1;
    SET FECHA_ACTUAL = FECHA_INICIO;
    
    SELECT MAX(NUMERO)+1 INTO NUMERO_HUECO
		FROM HUECOS;
	IF NUMERO_HUECO IS NULL THEN SET NUMERO_HUECO = 1;
    END IF;
    
    WHILE CONTADOR <= NUM_SEMANAS DO /*PARA REPETIR TANTAS SEMANAS COMO SE SOLICITE POR PARAMETRO*/
		WHILE DIA_SEMANA < 7 DO /*REPITE DE LUNES A SABADO*/
			WHILE HORA_ACTUAL < HORA_FIN DO
            
				INSERT	INTO HUECOS
				(NUMERO, HORA,DIA, CABINA)
				SELECT
					NUMERO_HUECO,
					HORA_ACTUAL,
					FECHA_ACTUAL,
					ID_CABINA
						FROM CABINAS;
                    
				SET HORA_ACTUAL = ADDTIME(HORA_ACTUAL,"01:00:00");
				SET NUMERO_HUECO = NUMERO_HUECO + 1;    
			END WHILE;
            
            SET FECHA_ACTUAL = ADDDATE(FECHA_ACTUAL, INTERVAL 1 DAY);
            SET HORA_ACTUAL = "11:00:00";
            SET DIA_SEMANA = DIA_SEMANA +1;
		END WHILE;
        SET FECHA_ACTUAL = FECHA_INICIO + INTERVAL CONTADOR WEEK;
        SET DIA_SEMANA = 1;
		SET CONTADOR = CONTADOR + 1;
	END WHILE;

END$$