DELIMITER $$

DROP PROCEDURE IF EXISTS CREAR_HUECOS_SEMANALES$$
CREATE PROCEDURE CREAR_HUECOS_SEMANALES(IN LUNES_INICIO DATE, IN NUM_SEMANAS INT UNSIGNED)
MODIFIES SQL DATA
BEGIN
	DECLARE HORA_ACTUAL TIME;
    DECLARE HORA_FIN TIME;
    DECLARE CONTADOR_SEMANA INT;
    DECLARE CONTADOR_DIA_SEMANA INT;
    DECLARE FECHA_ACTUAL DATE;
    DECLARE NUMERO_HUECO INT;
    
    IF WEEKDAY(LUNES_INICIO) != 0  /*NOS ASEGURAMOS QUE EL DIA INTRODUCIDO COMO PARAMETRO ES UN LUNES*/
		THEN SIGNAL SQLSTATE '45001' SET MESSAGE_TEXT = "EL DIA INTRODUCIDO COMO FECHA DE INICIO DEBE SER UN LUNES";
	END IF;
    
    SET HORA_ACTUAL = "11:00:00";
    SET HORA_FIN = "20:00:00";
    SET CONTADOR_SEMANA = 1;
    SET CONTADOR_DIA_SEMANA = 1;
    SET FECHA_ACTUAL = LUNES_INICIO;
    
    SELECT MAX(NUMERO)+1 INTO NUMERO_HUECO
		FROM HUECOS;
	IF NUMERO_HUECO IS NULL THEN SET NUMERO_HUECO = 1;
    END IF;
    
    
    
    WHILE CONTADOR_SEMANA <= NUM_SEMANAS DO /*PARA REPETIR TANTAS SEMANAS COMO SE SOLICITE POR PARÁMETRO*/
		WHILE CONTADOR_DIA_SEMANA <= 6 DO /*REPITE DE LUNES A SÁBADO, LOS DOMINGOS NO SE ABRE*/
			WHILE HORA_ACTUAL < HORA_FIN DO
            
				INSERT	INTO HUECOS
				(NUMERO, HORA,DIA, CABINA)
				SELECT
					NUMERO_HUECO,
					HORA_ACTUAL,
					FECHA_ACTUAL,
					ID_CABINA
						FROM CABINAS;
                    
				SET HORA_ACTUAL = ADDTIME(HORA_ACTUAL,"01:00:00");
				SET NUMERO_HUECO = NUMERO_HUECO + 1;    
			END WHILE;
            
            SET FECHA_ACTUAL = ADDDATE(FECHA_ACTUAL, INTERVAL 1 DAY);
            SET HORA_ACTUAL = "11:00:00";
            SET CONTADOR_DIA_SEMANA = CONTADOR_DIA_SEMANA +1;
		END WHILE;
        SET FECHA_ACTUAL = LUNES_INICIO + INTERVAL CONTADOR_SEMANA WEEK;
        SET CONTADOR_DIA_SEMANA = 1;
		SET CONTADOR_SEMANA = CONTADOR_SEMANA + 1;
	END WHILE;

END$$