/*PROCEDIMIENTO RESERVAR HUECOS CLIENTE*/
DELIMITER $$

DROP PROCEDURE IF EXISTS RESERVAR_HUECOS$$
CREATE PROCEDURE RESERVAR_HUECOS(
										IN DIA_CITA DATE,
										IN HORA_CITA TIME,
										IN CANTIDAD_HUECOS INT UNSIGNED,
										IN NUEVA_CABINA INT UNSIGNED,
										IN CLAVE_CITA INT UNSIGNED
								)
MODIFIES SQL DATA
BEGIN
	DECLARE CONTADOR_HUECOS INT DEFAULT 1;
    DECLARE HORA_ACTUAL TIME;
    DECLARE CITA_HUECO INT UNSIGNED;
    
    SET HORA_ACTUAL = HORA_CITA;
    
    WHILE CONTADOR_HUECOS <= CANTIDAD_HUECOS DO
		SELECT CITA INTO CITA_HUECO
        FROM HUECOS
        WHERE CONCAT(DIA,HORA,CABINA) = CONCAT(DIA_CITA,HORA_ACTUAL,NUEVA_CABINA);
        
		IF CITA IS NOT NULL THEN
			SIGNAL SQLSTATE '45100' SET MESSAGE_TEXT = "ERROR: LOS HUECOS YA ESTÁN ASIGNADOS A OTRA CITA";
		ELSE
			UPDATE HUECOS
            SET CITA = CLAVE_CITA
            WHERE CONCAT(DIA,HORA,CABINA) = CONCAT(DIA_CITA,HORA_ACTUAL,NUEVA_CABINA);
            
            SET HORA_ACTUAL = ADDTIME(HORA_ACTUAL, "01:00:00");
            SET CONTADOR_HUECOS = CONTADOR_HUECOS + 1;
		END IF;
	END WHILE;
END$$