/*PROCEDIMIENTO ASIGNAR CITA A CLIENTE*/
DELIMITER $$

DROP PROCEDURE IF EXISTS ASGINAR_CITA_CLIENTE$$
CREATE PROCEDURE ASIGNAR_CITA_CLIENTE(
										IN CLAVE_CITA INT UNSIGNED,
                                        IN CLAVE_CLIENTE INT UNSIGNED
									 )
MODIFIES SQL DATA
BEGIN
	INSERT INTO CITAS_CLIENTES
    (CITA,CLIENTE)
    VALUES
    (CLAVE_CITA,CLAVE_CLIENTE);

END$$