/*PROCEDIMIENTO PARA INSERTAR TUTORES LEGALES*/
DELIMITER $$

DROP PROCEDURE IF EXISTS CREAR_NUEVO_TUTOR$$
CREATE PROCEDURE CREAR_NUEVO_TUTOR(
									IN DNI_TUTOR CHAR(9),
                                    IN NOMBRE_TUTOR VARCHAR(50),
                                    IN FECHA_NAC_TUTOR DATE,
                                    IN TELEF_TUTOR VARCHAR(15)
								  )
MODIFIES SQL DATA
BEGIN
	INSERT INTO TUTORES_LEGALES
    (DNI,NOMBRE,FECHA_NACIMIENTO,TELEFONO)
    VALUES
    (
		DNI_TUTOR,
        NOMBRE_TUTOR,
        FECHA_NAC_TUTOR,
        TELEF_TUTOR
    );
END$$