/*CREAR TRIGGER QUE VERIFIQUE QUE SOLO SE PUEDEN RESERVAR CITAS DE PIERCING
EN UNA CABINA HABILITADA PARA ELLO*/
DELIMITER $$

DROP TRIGGER IF EXISTS VIGILAR_CABINA_PIERCING_I$$
CREATE TRIGGER VIGILAR_CABINA_PIERCING_I
BEFORE INSERT ON CITAS
FOR EACH ROW
BEGIN
	IF NEW.TIPO = "PIERCING"
		THEN IF NEW.CABINA NOT IN (
									SELECT	ID_CABINA
										FROM CABINAS 
										WHERE PUEDE_HACER_PIERCING IS TRUE
                                  ) 
			THEN SIGNAL SQLSTATE "45101" SET MESSAGE_TEXT = "ERROR: NO ES POSIBLE ASIGNAR CITA DE PIERCING EN CABINA NO HABILITADA PARA ELLO";
		END IF;
	END IF;
END$$

DROP TRIGGER IF EXISTS VIGILAR_CABINA_PIERCING_U$$
CREATE TRIGGER VIGILAR_CABINA_PIERCING_U
BEFORE UPDATE ON CITAS
FOR EACH ROW
BEGIN
	IF NEW.TIPO <> OLD.TIPO
		THEN SIGNAL SQLSTATE '45006' SET MESSAGE_TEXT = 'ERROR: NO ES POSIBLE CAMBIAR EL TIPO DE CITA';
	END IF;
    
	IF NEW.TIPO = "PIERCING"
		THEN IF NEW.CABINA NOT IN (
									SELECT	ID_CABINA
										FROM CABINAS 
										WHERE PUEDE_HACER_PIERCING IS TRUE
                                  ) 
			THEN SIGNAL SQLSTATE "45101" SET MESSAGE_TEXT = "ERROR: NO ES POSIBLE ASIGNAR CITA DE PIERCING EN CABINA NO HABILITADA PARA ELLO";
		END IF;
	END IF;
END$$