/*DISPARADORES QUE VERIFICAN QUE UNA CITA DE TIPO TATUAJE SEA REALIZADA POR UN TATUADOR
O UNA CITA DE PIERCING SEA REALIZADA POR UN ANILLADOR*/

DELIMITER $$
USE ESTUDIO_TATTOO$$

DROP TRIGGER IF EXISTS VIGILAR_TRABAJADOR_CITA_I$$
CREATE TRIGGER VIGILAR_TRABAJADOR_CITA_I
BEFORE INSERT ON CITAS
FOR EACH ROW
BEGIN
	IF NEW.TIPO = 'TATUAJE'
		THEN CALL VALIDAR_CITA_TATUAJE(NEW.TATUADOR,NEW.ANILLADOR);
	END IF;
    
	IF NEW.TIPO = 'PIERCING'
		THEN CALL VALIDAR_CITA_PIERCING(NEW.ANILLADOR, NEW.TATUADOR);
	END IF;
END$$

DROP TRIGGER IF EXISTS VIGILAR_TRABAJADOR_CITA_U$$
CREATE TRIGGER VIGILAR_TRABAJADOR_CITA_U
BEFORE UPDATE ON CITAS
FOR EACH ROW
BEGIN
	IF NEW.TIPO <> OLD.TIPO
		THEN SIGNAL SQLSTATE '45006' SET MESSAGE_TEXT = 'ERROR: NO ES POSIBLE CAMBIAR EL TIPO DE CITA';
	END IF;
    
	IF NEW.TIPO = 'TATUAJE'
		THEN CALL VALIDAR_CITA_TATUAJE(NEW.TATUADOR, NEW.ANILLADOR);
	END IF;
    
	IF NEW.TIPO = 'PIERCING'
		THEN CALL VALIDAR_CITA_PIERCING(NEW.ANILLADOR, NEW.TATUADOR);
	END IF;

END$$